--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDENES
--------------------------------------------------------

  CREATE TABLE "USUARIO02"."ORDENES" 
   (	"ORDENID" NUMBER(*,0), 
	"EMPLEADOS_EMPLEADOID" NUMBER(*,0), 
	"CLIENTES_CLIENTEID" NUMBER(*,0), 
	"FECHAORDEN" DATE, 
	"DESCUENTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USUARIO02.ORDENES
SET DEFINE OFF;
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('1','2','1',to_date('05/01/2025','DD/MM/RRRR'),'5');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('2','3','2',to_date('10/01/2025','DD/MM/RRRR'),'0');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('3','4','3',to_date('15/02/2025','DD/MM/RRRR'),'10');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('4','5','4',to_date('01/03/2025','DD/MM/RRRR'),'0');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('5','6','5',to_date('10/03/2025','DD/MM/RRRR'),'5');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('6','7','6',to_date('05/04/2025','DD/MM/RRRR'),'0');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('7','8','7',to_date('12/05/2025','DD/MM/RRRR'),'8');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('8','9','8',to_date('01/06/2025','DD/MM/RRRR'),'0');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('9','10','9',to_date('25/06/2025','DD/MM/RRRR'),'12');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('10','1','10',to_date('04/07/2025','DD/MM/RRRR'),'0');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('1001','1','1',to_date('02/09/2024','DD/MM/RRRR'),'0');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('1002','2','1',to_date('06/09/2024','DD/MM/RRRR'),'0');
Insert into USUARIO02.ORDENES (ORDENID,EMPLEADOS_EMPLEADOID,CLIENTES_CLIENTEID,FECHAORDEN,DESCUENTO) values ('1003','1','2',to_date('07/09/2024','DD/MM/RRRR'),'0');
--------------------------------------------------------
--  DDL for Index ORDENES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO02"."ORDENES_PK" ON "USUARIO02"."ORDENES" ("ORDENID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ORDENES
--------------------------------------------------------

  ALTER TABLE "USUARIO02"."ORDENES" MODIFY ("ORDENID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO02"."ORDENES" MODIFY ("EMPLEADOS_EMPLEADOID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO02"."ORDENES" MODIFY ("CLIENTES_CLIENTEID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO02"."ORDENES" MODIFY ("FECHAORDEN" NOT NULL ENABLE);
  ALTER TABLE "USUARIO02"."ORDENES" ADD CONSTRAINT "ORDENES_PK" PRIMARY KEY ("ORDENID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDENES
--------------------------------------------------------

  ALTER TABLE "USUARIO02"."ORDENES" ADD CONSTRAINT "ORDENES_CLIENTES_FK" FOREIGN KEY ("CLIENTES_CLIENTEID")
	  REFERENCES "USUARIO02"."CLIENTES" ("CLIENTEID") ENABLE;
  ALTER TABLE "USUARIO02"."ORDENES" ADD CONSTRAINT "ORDENES_EMPLEADOS_FK" FOREIGN KEY ("EMPLEADOS_EMPLEADOID")
	  REFERENCES "USUARIO02"."EMPLEADOS" ("EMPLEADOID") ENABLE;
