--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DIM_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "USUARIO02"."DIM_PRODUCTO" 
   (	"PRODUCTOID" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"PRECIOUNITARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USUARIO02.DIM_PRODUCTO
SET DEFINE OFF;
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('1','Laptop HP 15"','850');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('2','Mouse Logitech','25');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('3','Teclado Mecánico','65');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('4','Monitor Samsung 24"','180');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('5','Impresora Epson','210');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('6','Disco Duro 1TB','75');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('7','Memoria USB 64GB','18');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('8','Silla Ergonómica','140');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('9','Tablet Lenovo','250');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('10','Router TP-Link','50');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('11','Webcam Full HD','60');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('12','Auriculares Bluetooth','80');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('13','Micrófono Profesional','120');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('14','Smartwatch Samsung','199');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('15','Cámara de Seguridad','150');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('16','Proyector Epson','350');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('17','SSD 512GB','95');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('18','Cargador Universal','20');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('19','Hub USB-C','45');
Insert into USUARIO02.DIM_PRODUCTO (PRODUCTOID,DESCRIPCION,PRECIOUNITARIO) values ('20','Altavoces JBL','110');
--------------------------------------------------------
--  DDL for Index SYS_C008262
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO02"."SYS_C008262" ON "USUARIO02"."DIM_PRODUCTO" ("PRODUCTOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DIM_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "USUARIO02"."DIM_PRODUCTO" ADD PRIMARY KEY ("PRODUCTOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
