--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DIM_TIEMPO
--------------------------------------------------------

  CREATE TABLE "USUARIO02"."DIM_TIEMPO" 
   (	"TIEMPOID" NUMBER(*,0), 
	"FECHA" DATE, 
	"AÑO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"TRIMESTRE" NUMBER(*,0), 
	"DIASEMANA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USUARIO02.DIM_TIEMPO
SET DEFINE OFF;
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('1',to_date('05/01/2025','DD/MM/RRRR'),'2025','1','1','Domingo');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('2',to_date('10/01/2025','DD/MM/RRRR'),'2025','1','1','Viernes');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('3',to_date('15/02/2025','DD/MM/RRRR'),'2025','2','1','Sábado');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('4',to_date('01/03/2025','DD/MM/RRRR'),'2025','3','1','Sábado');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('5',to_date('18/03/2025','DD/MM/RRRR'),'2025','3','1','Martes');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('6',to_date('07/04/2025','DD/MM/RRRR'),'2025','4','2','Lunes');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('7',to_date('25/04/2025','DD/MM/RRRR'),'2025','4','2','Viernes');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('8',to_date('02/05/2025','DD/MM/RRRR'),'2025','5','2','Viernes');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('9',to_date('15/05/2025','DD/MM/RRRR'),'2025','5','2','Jueves');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('10',to_date('01/06/2025','DD/MM/RRRR'),'2025','6','2','Domingo');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('11',to_date('15/06/2025','DD/MM/RRRR'),'2025','6','2','Domingo');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('12',to_date('03/07/2025','DD/MM/RRRR'),'2025','7','3','Jueves');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('13',to_date('25/07/2025','DD/MM/RRRR'),'2025','7','3','Viernes');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('14',to_date('10/08/2025','DD/MM/RRRR'),'2025','8','3','Domingo');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('15',to_date('25/08/2025','DD/MM/RRRR'),'2025','8','3','Lunes');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('16',to_date('05/09/2025','DD/MM/RRRR'),'2025','9','3','Viernes');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('17',to_date('22/09/2025','DD/MM/RRRR'),'2025','9','3','Lunes');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('18',to_date('02/10/2025','DD/MM/RRRR'),'2025','10','4','Jueves');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('19',to_date('15/10/2025','DD/MM/RRRR'),'2025','10','4','Miércoles');
Insert into USUARIO02.DIM_TIEMPO (TIEMPOID,FECHA,"AÑO",MES,TRIMESTRE,DIASEMANA) values ('20',to_date('01/11/2025','DD/MM/RRRR'),'2025','11','4','Sábado');
--------------------------------------------------------
--  DDL for Index SYS_C008263
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO02"."SYS_C008263" ON "USUARIO02"."DIM_TIEMPO" ("TIEMPOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DIM_TIEMPO
--------------------------------------------------------

  ALTER TABLE "USUARIO02"."DIM_TIEMPO" ADD PRIMARY KEY ("TIEMPOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
