--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DETALLE_ORDENES
--------------------------------------------------------

  CREATE TABLE "USUARIO02"."DETALLE_ORDENES" 
   (	"ORDENES_ORDENID" NUMBER(*,0), 
	"DETALLEID" NUMBER(*,0), 
	"PRODUCTOS_PRODUCTOID" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USUARIO02.DETALLE_ORDENES
SET DEFINE OFF;
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('1','1','1','3');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('1','2','2','2');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('2','1','3','1');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('2','2','4','2');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('3','1','5','1');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('4','1','6','5');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('5','1','7','3');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('6','1','8','1');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('7','1','9','4');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('8','1','10','2');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('1001','1','1','3');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('1001','2','2','2');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('1002','1','3','5');
Insert into USUARIO02.DETALLE_ORDENES (ORDENES_ORDENID,DETALLEID,PRODUCTOS_PRODUCTOID,CANTIDAD) values ('1003','1','4','10');
--------------------------------------------------------
--  DDL for Index DETALLE_ORDENES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO02"."DETALLE_ORDENES_PK" ON "USUARIO02"."DETALLE_ORDENES" ("ORDENES_ORDENID", "DETALLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_ACTUALIZARVALORESEMPLEADOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USUARIO02"."TRG_ACTUALIZARVALORESEMPLEADOS" 
AFTER INSERT OR UPDATE OR DELETE
ON DETALLE_ORDENES
FOR EACH ROW
DECLARE
    v_EmpleadoID ORDENES.EMPLEADOS_EMPLEADOID%TYPE;
    v_CantidadOrdenes NUMBER;
    v_ValorOrdenes NUMBER;
BEGIN
    -- Obtener el empleado relacionado a la orden afectada
    IF INSERTING OR UPDATING THEN
        SELECT EMPLEADOS_EMPLEADOID
        INTO v_EmpleadoID
        FROM ORDENES
        WHERE ORDENID = :NEW.ORDENES_ORDENID;
    ELSIF DELETING THEN
        SELECT EMPLEADOS_EMPLEADOID
        INTO v_EmpleadoID
        FROM ORDENES
        WHERE ORDENID = :OLD.ORDENES_ORDENID;
    END IF;

    -- Calcular los totales actualizados para ese empleado
    SELECT 
        COUNT(DISTINCT O.ORDENID),
        NVL(SUM(DO.CANTIDAD * P.PRECIOUNIT),0)
    INTO 
        v_CantidadOrdenes,
        v_ValorOrdenes
    FROM ORDENES O
    JOIN DETALLE_ORDENES DO ON O.ORDENID = DO.ORDENES_ORDENID
    JOIN PRODUCTOS P ON DO.PRODUCTOS_PRODUCTOID = P.PRODUCTOID
    WHERE O.EMPLEADOS_EMPLEADOID = v_EmpleadoID;

    -- Actualizar los valores en la tabla EMPLEADOS
    UPDATE EMPLEADOS
    SET 
        CantidadOrdenes = v_CantidadOrdenes,
        ValorOrdenes = v_ValorOrdenes
    WHERE EMPLEADOID = v_EmpleadoID;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;

/
ALTER TRIGGER "USUARIO02"."TRG_ACTUALIZARVALORESEMPLEADOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ACTUALIZA_EXISTENCIA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USUARIO02"."TRG_ACTUALIZA_EXISTENCIA" 
AFTER INSERT OR UPDATE OR DELETE
ON DETALLE_ORDENES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE PRODUCTOS
        SET EXISTENCIA = EXISTENCIA - :NEW.CANTIDAD
        WHERE PRODUCTOID = :NEW.PRODUCTOID;

    ELSIF UPDATING THEN
        UPDATE PRODUCTOS
        SET EXISTENCIA = EXISTENCIA + (:OLD.CANTIDAD - :NEW.CANTIDAD)
        WHERE PRODUCTOID = :OLD.PRODUCTOID;

    ELSIF DELETING THEN
        UPDATE PRODUCTOS
        SET EXISTENCIA = EXISTENCIA + :OLD.CANTIDAD
        WHERE PRODUCTOID = :OLD.PRODUCTOID;
    END IF;
END;

/
ALTER TRIGGER "USUARIO02"."TRG_ACTUALIZA_EXISTENCIA" ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_ORDENES
--------------------------------------------------------

  ALTER TABLE "USUARIO02"."DETALLE_ORDENES" MODIFY ("ORDENES_ORDENID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO02"."DETALLE_ORDENES" MODIFY ("DETALLEID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO02"."DETALLE_ORDENES" MODIFY ("PRODUCTOS_PRODUCTOID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO02"."DETALLE_ORDENES" ADD CONSTRAINT "DETALLE_ORDENES_PK" PRIMARY KEY ("ORDENES_ORDENID", "DETALLEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_ORDENES
--------------------------------------------------------

  ALTER TABLE "USUARIO02"."DETALLE_ORDENES" ADD CONSTRAINT "DETALLE_ORDENES_ORDENES_FK" FOREIGN KEY ("ORDENES_ORDENID")
	  REFERENCES "USUARIO02"."ORDENES" ("ORDENID") ENABLE;
  ALTER TABLE "USUARIO02"."DETALLE_ORDENES" ADD CONSTRAINT "DETALLE_ORDENES_PRODUCTOS_FK" FOREIGN KEY ("PRODUCTOS_PRODUCTOID")
	  REFERENCES "USUARIO02"."PRODUCTOS" ("PRODUCTOID") ENABLE;
