-- ============================================================================
-- PROYECTO OLAP - SISTEMA DE PEDIDOS
-- ============================================================================
-- Archivo: VistasOLAP_PowerBI_Oracle.sql
-- Descripcion: Vistas optimizadas para conexion con Power BI (ORACLE)
-- Base de Datos: Oracle Database 21c
-- Fecha: Diciembre 2025
-- ============================================================================

SET SERVEROUTPUT ON;

-- ============================================================================
-- ELIMINAR VISTAS EXISTENTES
-- ============================================================================

BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_VENTASCOMPLETAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_VENTASPRODUCTOPROVEEDOR'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_VENTASMODALIDADPAGO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_VENTASEMPLEADO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_RESUMENVENTASANUAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_ANALISISIVA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_CALENDARIO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================================
-- VISTA 1: Ventas Completas (Vista Principal)
-- ============================================================================

CREATE OR REPLACE VIEW VW_VENTASCOMPLETAS AS
SELECT 
    -- Claves
    f.FACTVENTAID AS VENTAKEY,
    f.PEDIDOID_OLTP AS PEDIDOID,
    
    -- Dimension Tiempo
    t.FECHA,
    t.ANIO,
    t.NOMBRESEMESTRE AS SEMESTRE,
    t.NOMBRETRIMESTRE AS TRIMESTRE,
    t.NOMBREMES AS MES,
    t.SEMANA,
    t.NOMBREDIA AS DIASEMANA,
    t.ESFINDESEMANA,
    t.ESDIALABORAL,
    t.ANIOMES,
    t.ANIOTRIMESTRE,
    
    -- Dimension Producto
    p.CODIGO AS CODIGOPRODUCTO,
    p.NOMBRE AS PRODUCTO,
    p.NOMBRECATEGORIA AS CATEGORIA,
    p.NOMBREPROVEEDOR AS PROVEEDOR,
    p.PRECIOUNITARIO AS PRECIOLISTA,
    p.PORCENTAJEIVA,
    p.TIPOIVA,
    
    -- Dimension Cliente
    c.CODIGO AS CODIGOCLIENTE,
    c.NOMBRECOMPLETO AS CLIENTE,
    c.CIUDAD AS CIUDADCLIENTE,
    c.PAIS AS PAISCLIENTE,
    uc.REGION AS REGIONCLIENTE,
    
    -- Dimension Proveedor
    prov.CIUDAD AS CIUDADPROVEEDOR,
    prov.PAIS AS PAISPROVEEDOR,
    uprov.REGION AS REGIONPROVEEDOR,
    
    -- Dimension Empleado
    e.CODIGO AS CODIGOEMPLEADO,
    e.NOMBRECOMPLETO AS EMPLEADO,
    e.CARGO AS CARGOEMPLEADO,
    
    -- Dimension Modalidad de Pago
    mp.DESCRIPCION AS MODALIDADPAGO,
    mp.TIPOPAGO,
    mp.CUOTAS,
    mp.DESCRIPCIONCOMPLETA AS MODALIDADPAGODETALLE,
    mp.ESTARJETA,
    
    -- Metricas
    f.CANTIDAD,
    f.PRECIOUNITARIO AS PRECIOVENTA,
    f.MONTOSUBTOTAL AS SUBTOTAL,
    f.MONTOIVA AS IVA,
    f.MONTOTOTAL AS TOTAL

FROM FACTVENTAS f
JOIN DIMTIEMPO t ON f.TIEMPOKEY = t.TIEMPOKEY
JOIN DIMPRODUCTO p ON f.PRODUCTOKEY = p.PRODUCTOKEY
JOIN DIMCLIENTE c ON f.CLIENTEKEY = c.CLIENTEKEY
JOIN DIMUBICACION uc ON c.UBICACIONKEY = uc.UBICACIONKEY
JOIN DIMPROVEEDOR prov ON f.PROVEEDORKEY = prov.PROVEEDORKEY
JOIN DIMUBICACION uprov ON prov.UBICACIONKEY = uprov.UBICACIONKEY
JOIN DIMEMPLEADO e ON f.EMPLEADOKEY = e.EMPLEADOKEY
JOIN DIMMODALIDADPAGO mp ON f.MODALIDADKEY = mp.MODALIDADKEY;

BEGIN DBMS_OUTPUT.PUT_LINE('Vista VW_VENTASCOMPLETAS creada.'); END;
/

-- ============================================================================
-- VISTA 2: Hecho (a) - Ventas por Producto, Proveedor, Tiempo, Ubicacion
-- ============================================================================

CREATE OR REPLACE VIEW VW_VENTASPRODUCTOPROVEEDOR AS
SELECT 
    t.ANIO,
    t.NOMBRETRIMESTRE AS TRIMESTRE,
    t.NOMBREMES AS MES,
    t.ANIOMES,
    
    p.NOMBRE AS PRODUCTO,
    p.CODIGO AS CODIGOPRODUCTO,
    p.NOMBRECATEGORIA AS CATEGORIA,
    
    prov.NOMBRE AS PROVEEDOR,
    prov.CIUDAD AS CIUDADPROVEEDOR,
    u.REGION AS REGIONPROVEEDOR,
    u.PAIS AS PAISPROVEEDOR,
    
    COUNT(DISTINCT f.PEDIDOID_OLTP) AS NUMEROPEDIDOS,
    SUM(f.CANTIDAD) AS UNIDADESVENDIDAS,
    SUM(f.MONTOSUBTOTAL) AS SUBTOTAL,
    SUM(f.MONTOIVA) AS IVA,
    SUM(f.MONTOTOTAL) AS VENTATOTAL,
    AVG(f.MONTOTOTAL) AS PROMEDIOVENTA

FROM FACTVENTAS f
JOIN DIMTIEMPO t ON f.TIEMPOKEY = t.TIEMPOKEY
JOIN DIMPRODUCTO p ON f.PRODUCTOKEY = p.PRODUCTOKEY
JOIN DIMPROVEEDOR prov ON f.PROVEEDORKEY = prov.PROVEEDORKEY
JOIN DIMUBICACION u ON prov.UBICACIONKEY = u.UBICACIONKEY
GROUP BY 
    t.ANIO, t.TRIMESTRE, t.NOMBRETRIMESTRE, t.MES, t.NOMBREMES, t.ANIOMES,
    p.NOMBRE, p.CODIGO, p.NOMBRECATEGORIA,
    prov.NOMBRE, prov.CIUDAD, u.REGION, u.PAIS;

BEGIN DBMS_OUTPUT.PUT_LINE('Vista VW_VENTASPRODUCTOPROVEEDOR creada.'); END;
/

-- ============================================================================
-- VISTA 3: Hecho (b) - Ventas por Modalidad de Pago, Tiempo, Region
-- ============================================================================

CREATE OR REPLACE VIEW VW_VENTASMODALIDADPAGO AS
SELECT 
    t.ANIO,
    t.NOMBRETRIMESTRE AS TRIMESTRE,
    t.NOMBREMES AS MES,
    t.ANIOMES,
    t.ESFINDESEMANA,
    
    mp.DESCRIPCION AS MODALIDADPAGO,
    mp.TIPOPAGO,
    mp.CUOTAS,
    mp.DESCRIPCIONCOMPLETA AS MODALIDADDETALLE,
    mp.ESTARJETA,
    
    u.REGION AS REGIONCLIENTE,
    u.CIUDAD AS CIUDADCLIENTE,
    u.PAIS AS PAISCLIENTE,
    
    COUNT(DISTINCT f.PEDIDOID_OLTP) AS NUMEROPEDIDOS,
    COUNT(DISTINCT f.CLIENTEKEY) AS CLIENTESUNICOS,
    SUM(f.CANTIDAD) AS UNIDADESVENDIDAS,
    SUM(f.MONTOSUBTOTAL) AS SUBTOTAL,
    SUM(f.MONTOIVA) AS IVA,
    SUM(f.MONTOTOTAL) AS VENTATOTAL,
    AVG(f.MONTOTOTAL) AS TICKETPROMEDIO

FROM FACTVENTAS f
JOIN DIMTIEMPO t ON f.TIEMPOKEY = t.TIEMPOKEY
JOIN DIMMODALIDADPAGO mp ON f.MODALIDADKEY = mp.MODALIDADKEY
JOIN DIMCLIENTE c ON f.CLIENTEKEY = c.CLIENTEKEY
JOIN DIMUBICACION u ON c.UBICACIONKEY = u.UBICACIONKEY
GROUP BY 
    t.ANIO, t.TRIMESTRE, t.NOMBRETRIMESTRE, t.MES, t.NOMBREMES, t.ANIOMES, t.ESFINDESEMANA,
    mp.DESCRIPCION, mp.TIPOPAGO, mp.CUOTAS, mp.DESCRIPCIONCOMPLETA, mp.ESTARJETA,
    u.REGION, u.CIUDAD, u.PAIS;

BEGIN DBMS_OUTPUT.PUT_LINE('Vista VW_VENTASMODALIDADPAGO creada.'); END;
/

-- ============================================================================
-- VISTA 4: Hecho (e) - Mejores Vendedores por Categoria, Tiempo, Ubicacion
-- ============================================================================

CREATE OR REPLACE VIEW VW_VENTASEMPLEADO AS
SELECT 
    t.ANIO,
    t.NOMBRETRIMESTRE AS TRIMESTRE,
    t.NOMBREMES AS MES,
    t.ANIOMES,
    
    e.CODIGO AS CODIGOEMPLEADO,
    e.NOMBRECOMPLETO AS EMPLEADO,
    e.CARGO,
    
    cat.NOMBRE AS CATEGORIA,
    
    u.REGION AS REGIONCLIENTE,
    u.CIUDAD AS CIUDADCLIENTE,
    
    mp.TIPOPAGO,
    mp.DESCRIPCION AS MODALIDADPAGO,
    
    COUNT(DISTINCT f.PEDIDOID_OLTP) AS NUMEROPEDIDOS,
    COUNT(DISTINCT f.CLIENTEKEY) AS CLIENTESATENDIDOS,
    SUM(f.CANTIDAD) AS UNIDADESVENDIDAS,
    SUM(f.MONTOSUBTOTAL) AS SUBTOTAL,
    SUM(f.MONTOIVA) AS IVA,
    SUM(f.MONTOTOTAL) AS VENTATOTAL

FROM FACTVENTAS f
JOIN DIMTIEMPO t ON f.TIEMPOKEY = t.TIEMPOKEY
JOIN DIMEMPLEADO e ON f.EMPLEADOKEY = e.EMPLEADOKEY
JOIN DIMCATEGORIA cat ON f.CATEGORIAKEY = cat.CATEGORIAKEY
JOIN DIMCLIENTE c ON f.CLIENTEKEY = c.CLIENTEKEY
JOIN DIMUBICACION u ON c.UBICACIONKEY = u.UBICACIONKEY
JOIN DIMMODALIDADPAGO mp ON f.MODALIDADKEY = mp.MODALIDADKEY
GROUP BY 
    t.ANIO, t.TRIMESTRE, t.NOMBRETRIMESTRE, t.MES, t.NOMBREMES, t.ANIOMES,
    e.CODIGO, e.NOMBRECOMPLETO, e.CARGO,
    cat.NOMBRE,
    u.REGION, u.CIUDAD,
    mp.TIPOPAGO, mp.DESCRIPCION;

BEGIN DBMS_OUTPUT.PUT_LINE('Vista VW_VENTASEMPLEADO creada.'); END;
/

-- ============================================================================
-- VISTA 5: Resumen Anual de Ventas (KPIs)
-- ============================================================================

CREATE OR REPLACE VIEW VW_RESUMENVENTASANUAL AS
SELECT 
    t.ANIO,
    t.NOMBRETRIMESTRE AS TRIMESTRE,
    t.NOMBREMES AS MES,
    
    COUNT(DISTINCT f.PEDIDOID_OLTP) AS TOTALPEDIDOS,
    COUNT(DISTINCT f.CLIENTEKEY) AS CLIENTESACTIVOS,
    COUNT(DISTINCT f.PRODUCTOKEY) AS PRODUCTOSVENDIDOS,
    SUM(f.CANTIDAD) AS UNIDADESTOTALES,
    SUM(f.MONTOSUBTOTAL) AS SUBTOTAL,
    SUM(f.MONTOIVA) AS IVARECAUDADO,
    SUM(f.MONTOTOTAL) AS VENTATOTAL,
    AVG(f.MONTOTOTAL) AS TICKETPROMEDIO,
    
    -- KPIs adicionales
    SUM(f.MONTOTOTAL) / NULLIF(COUNT(DISTINCT f.PEDIDOID_OLTP), 0) AS VENTAPROMPORPEDIDO,
    SUM(f.CANTIDAD) / NULLIF(COUNT(DISTINCT f.PEDIDOID_OLTP), 0) AS UNIDADESPROMPORPEDIDO

FROM FACTVENTAS f
JOIN DIMTIEMPO t ON f.TIEMPOKEY = t.TIEMPOKEY
GROUP BY 
    t.ANIO, t.TRIMESTRE, t.NOMBRETRIMESTRE, t.MES, t.NOMBREMES;

BEGIN DBMS_OUTPUT.PUT_LINE('Vista VW_RESUMENVENTASANUAL creada.'); END;
/

-- ============================================================================
-- VISTA 6: Analisis de IVA
-- ============================================================================

CREATE OR REPLACE VIEW VW_ANALISISIVA AS
SELECT 
    t.ANIO,
    t.NOMBRETRIMESTRE AS TRIMESTRE,
    t.NOMBREMES AS MES,
    
    p.TIPOIVA,
    p.PORCENTAJEIVA,
    p.NOMBRECATEGORIA AS CATEGORIA,
    
    COUNT(DISTINCT f.PEDIDOID_OLTP) AS NUMEROPEDIDOS,
    SUM(f.CANTIDAD) AS UNIDADESVENDIDAS,
    SUM(f.MONTOSUBTOTAL) AS BASEIMPONIBLE,
    SUM(f.MONTOIVA) AS IVARECAUDADO,
    SUM(f.MONTOTOTAL) AS TOTAL

FROM FACTVENTAS f
JOIN DIMTIEMPO t ON f.TIEMPOKEY = t.TIEMPOKEY
JOIN DIMPRODUCTO p ON f.PRODUCTOKEY = p.PRODUCTOKEY
GROUP BY 
    t.ANIO, t.TRIMESTRE, t.NOMBRETRIMESTRE, t.MES, t.NOMBREMES,
    p.TIPOIVA, p.PORCENTAJEIVA, p.NOMBRECATEGORIA;

BEGIN DBMS_OUTPUT.PUT_LINE('Vista VW_ANALISISIVA creada.'); END;
/

-- ============================================================================
-- VISTA 7: Calendario (Para relaciones en Power BI)
-- ============================================================================

CREATE OR REPLACE VIEW VW_CALENDARIO AS
SELECT 
    TIEMPOKEY,
    FECHA,
    ANIO,
    NOMBRESEMESTRE AS SEMESTRE,
    NOMBRETRIMESTRE AS TRIMESTRE,
    MES AS NUMEROMES,
    NOMBREMES AS MES,
    NOMBREMESCORTO AS MESCORTO,
    SEMANA,
    DIADELMES AS DIA,
    NOMBREDIA AS DIASEMANA,
    NOMBREDIACORTO AS DIASEMANACORTO,
    DIADELANIO,
    ESFINDESEMANA,
    ESDIALABORAL,
    ANIOMES,
    ANIOTRIMESTRE
FROM DIMTIEMPO;

BEGIN DBMS_OUTPUT.PUT_LINE('Vista VW_CALENDARIO creada.'); END;
/

-- ============================================================================
-- VERIFICACION
-- ============================================================================

SELECT '============================================================================' AS INFO FROM DUAL;
SELECT 'VISTAS OLAP PARA POWER BI - RESUMEN' AS INFO FROM DUAL;
SELECT '============================================================================' AS INFO FROM DUAL;

SELECT 
    VIEW_NAME AS VISTA,
    CREATED AS FECHA_CREACION
FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'VIEW'
AND VIEW_NAME LIKE 'VW_%'
ORDER BY VIEW_NAME;

SELECT '============================================================================' AS INFO FROM DUAL;
SELECT 'VISTAS CREADAS EXITOSAMENTE' AS INFO FROM DUAL;
SELECT '============================================================================' AS INFO FROM DUAL;

COMMIT;
