--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FACT_VENTAS
--------------------------------------------------------

  CREATE TABLE "USUARIO02"."FACT_VENTAS" 
   (	"VENTAID" NUMBER(*,0), 
	"PRODUCTOID" NUMBER(*,0), 
	"TIEMPOID" NUMBER(*,0), 
	"PEDIDOID" NUMBER(*,0), 
	"CANTIDADVENDIDA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USUARIO02.FACT_VENTAS
SET DEFINE OFF;
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('1','1','1','1','10');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('2','2','2','2','15');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('3','3','3','3','5');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('4','4','4','4','8');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('5','5','5','5','12');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('6','6','6','6','7');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('7','7','7','7','20');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('8','8','8','8','6');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('9','9','9','9','4');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('10','10','10','10','18');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('11','11','11','11','9');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('12','12','12','12','10');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('13','13','13','13','3');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('14','14','14','14','6');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('15','15','15','15','2');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('16','16','16','16','8');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('17','17','17','17','5');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('18','18','18','18','9');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('19','19','19','19','11');
Insert into USUARIO02.FACT_VENTAS (VENTAID,PRODUCTOID,TIEMPOID,PEDIDOID,CANTIDADVENDIDA) values ('20','20','20','20','7');
--------------------------------------------------------
--  DDL for Index SYS_C008265
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO02"."SYS_C008265" ON "USUARIO02"."FACT_VENTAS" ("VENTAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FACT_VENTAS
--------------------------------------------------------

  ALTER TABLE "USUARIO02"."FACT_VENTAS" ADD PRIMARY KEY ("VENTAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACT_VENTAS
--------------------------------------------------------

  ALTER TABLE "USUARIO02"."FACT_VENTAS" ADD FOREIGN KEY ("PRODUCTOID")
	  REFERENCES "USUARIO02"."DIM_PRODUCTO" ("PRODUCTOID") ENABLE;
  ALTER TABLE "USUARIO02"."FACT_VENTAS" ADD FOREIGN KEY ("TIEMPOID")
	  REFERENCES "USUARIO02"."DIM_TIEMPO" ("TIEMPOID") ENABLE;
  ALTER TABLE "USUARIO02"."FACT_VENTAS" ADD FOREIGN KEY ("PEDIDOID")
	  REFERENCES "USUARIO02"."DIM_PEDIDOS" ("PEDIDOID") ENABLE;
