--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLEADOS
--------------------------------------------------------

  CREATE TABLE "USUARIO02"."EMPLEADOS" 
   (	"EMPLEADOID" NUMBER(*,0), 
	"NOMBRE" CHAR(30 BYTE), 
	"APELLIDO" CHAR(30 BYTE), 
	"FECHA_NAC" DATE, 
	"EMPLEADOS_EMPLEADOID" NUMBER(*,0), 
	"EXTENSION" NUMBER(*,0), 
	"CANTIDADORDENES" NUMBER(10,0), 
	"VALORORDENES" NUMBER(12,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USUARIO02.EMPLEADOS
SET DEFINE OFF;
Insert into USUARIO02.EMPLEADOS (EMPLEADOID,NOMBRE,APELLIDO,FECHA_NAC,EMPLEADOS_EMPLEADOID,EXTENSION,CANTIDADORDENES,VALORORDENES) values ('1','Carlos                        ','Mendoza                       ',to_date('15/04/1985','DD/MM/RRRR'),null,'1001','5','10');
Insert into USUARIO02.EMPLEADOS (EMPLEADOID,NOMBRE,APELLIDO,FECHA_NAC,EMPLEADOS_EMPLEADOID,EXTENSION,CANTIDADORDENES,VALORORDENES) values ('2','María                        ','Suárez                       ',to_date('22/03/1990','DD/MM/RRRR'),'1','1002','5','10');
Insert into USUARIO02.EMPLEADOS (EMPLEADOID,NOMBRE,APELLIDO,FECHA_NAC,EMPLEADOS_EMPLEADOID,EXTENSION,CANTIDADORDENES,VALORORDENES) values ('3','Jorge                         ','Lozano                        ',to_date('10/11/1988','DD/MM/RRRR'),'1','1003','5','10');
Insert into USUARIO02.EMPLEADOS (EMPLEADOID,NOMBRE,APELLIDO,FECHA_NAC,EMPLEADOS_EMPLEADOID,EXTENSION,CANTIDADORDENES,VALORORDENES) values ('4','Laura                         ','García                       ',to_date('05/01/1992','DD/MM/RRRR'),'2','1004','5','10');
Insert into USUARIO02.EMPLEADOS (EMPLEADOID,NOMBRE,APELLIDO,FECHA_NAC,EMPLEADOS_EMPLEADOID,EXTENSION,CANTIDADORDENES,VALORORDENES) values ('5','Andrés                       ','Salazar                       ',to_date('09/07/1989','DD/MM/RRRR'),'2','1005','5','10');
Insert into USUARIO02.EMPLEADOS (EMPLEADOID,NOMBRE,APELLIDO,FECHA_NAC,EMPLEADOS_EMPLEADOID,EXTENSION,CANTIDADORDENES,VALORORDENES) values ('6','Verónica                     ','Paredes                       ',to_date('18/09/1993','DD/MM/RRRR'),'3','1006','5','10');
Insert into USUARIO02.EMPLEADOS (EMPLEADOID,NOMBRE,APELLIDO,FECHA_NAC,EMPLEADOS_EMPLEADOID,EXTENSION,CANTIDADORDENES,VALORORDENES) values ('7','Mateo                         ','Reyes                         ',to_date('01/10/1991','DD/MM/RRRR'),'3','1007','5','10');
Insert into USUARIO02.EMPLEADOS (EMPLEADOID,NOMBRE,APELLIDO,FECHA_NAC,EMPLEADOS_EMPLEADOID,EXTENSION,CANTIDADORDENES,VALORORDENES) values ('8','Carolina                      ','Ríos                         ',to_date('25/12/1987','DD/MM/RRRR'),'4','1008','5','10');
Insert into USUARIO02.EMPLEADOS (EMPLEADOID,NOMBRE,APELLIDO,FECHA_NAC,EMPLEADOS_EMPLEADOID,EXTENSION,CANTIDADORDENES,VALORORDENES) values ('9','Santiago                      ','Calle                         ',to_date('12/06/1984','DD/MM/RRRR'),'4','1009','5','10');
Insert into USUARIO02.EMPLEADOS (EMPLEADOID,NOMBRE,APELLIDO,FECHA_NAC,EMPLEADOS_EMPLEADOID,EXTENSION,CANTIDADORDENES,VALORORDENES) values ('10','Patricia                      ','Morales                       ',to_date('20/08/1995','DD/MM/RRRR'),'5','1010','5','10');
--------------------------------------------------------
--  DDL for Index EMPLEADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO02"."EMPLEADOS_PK" ON "USUARIO02"."EMPLEADOS" ("EMPLEADOID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "USUARIO02"."EMPLEADOS" MODIFY ("EMPLEADOID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO02"."EMPLEADOS" ADD CONSTRAINT "EMPLEADOS_PK" PRIMARY KEY ("EMPLEADOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "USUARIO02"."EMPLEADOS" ADD CONSTRAINT "EMPLEADOS_EMPLEADOS_FK" FOREIGN KEY ("EMPLEADOS_EMPLEADOID")
	  REFERENCES "USUARIO02"."EMPLEADOS" ("EMPLEADOID") ENABLE;
