-- ============================================================================
-- PROYECTO OLAP - SISTEMA DE PEDIDOS
-- ============================================================================
-- Archivo: Tablas_Oracle.sql
-- Descripcion: Esquema OLTP completo para sistema de pedidos (ORACLE)
-- Base de Datos: Oracle Database 21c
-- Fecha: Diciembre 2025
-- ============================================================================

-- ============================================================================
-- LIMPIEZA DE TABLAS EXISTENTES (en orden de dependencias)
-- ============================================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DETALLE_PEDIDO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PEDIDO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MODALIDAD_PAGO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EMPLEADO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PROVEEDOR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CATEGORIA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Eliminar secuencias si existen
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CATEGORIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PROVEEDOR'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLEADO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MODALIDAD_PAGO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PRODUCTO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PEDIDO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DETALLE_PEDIDO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================================
-- CREAR SECUENCIAS (equivalente a IDENTITY en SQL Server)
-- ============================================================================

CREATE SEQUENCE SEQ_CATEGORIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROVEEDOR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EMPLEADO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MODALIDAD_PAGO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCTO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PEDIDO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DETALLE_PEDIDO START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================================
-- TABLA: CATEGORIA
-- ============================================================================

CREATE TABLE CATEGORIA (
    CATEGORIAID     NUMBER(10) DEFAULT SEQ_CATEGORIA.NEXTVAL PRIMARY KEY,
    CODIGO          VARCHAR2(10) NOT NULL UNIQUE,
    NOMBRE          VARCHAR2(100) NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    FECHACREACION   TIMESTAMP DEFAULT SYSTIMESTAMP,
    ACTIVO          NUMBER(1) DEFAULT 1
);

-- ============================================================================
-- TABLA: PROVEEDOR
-- ============================================================================

CREATE TABLE PROVEEDOR (
    PROVEEDORID     NUMBER(10) DEFAULT SEQ_PROVEEDOR.NEXTVAL PRIMARY KEY,
    CODIGO          VARCHAR2(20) NOT NULL UNIQUE,
    NOMBRE          VARCHAR2(200) NOT NULL,
    NOMBRECONTACTO  VARCHAR2(150),
    TELEFONO        VARCHAR2(20),
    EMAIL           VARCHAR2(150),
    DIRECCION       VARCHAR2(300),
    CIUDAD          VARCHAR2(100) NOT NULL,
    PAIS            VARCHAR2(100) DEFAULT 'Ecuador' NOT NULL,
    FECHACREACION   TIMESTAMP DEFAULT SYSTIMESTAMP,
    ACTIVO          NUMBER(1) DEFAULT 1
);

-- ============================================================================
-- TABLA: EMPLEADO
-- ============================================================================

CREATE TABLE EMPLEADO (
    EMPLEADOID      NUMBER(10) DEFAULT SEQ_EMPLEADO.NEXTVAL PRIMARY KEY,
    CODIGO          VARCHAR2(20) NOT NULL UNIQUE,
    NOMBRECOMPLETO  VARCHAR2(200) NOT NULL,
    CARGO           VARCHAR2(100) DEFAULT 'Vendedor' NOT NULL,
    EMAIL           VARCHAR2(150),
    TELEFONO        VARCHAR2(20),
    FECHACONTRATACION DATE DEFAULT SYSDATE NOT NULL,
    ACTIVO          NUMBER(1) DEFAULT 1
);

-- ============================================================================
-- TABLA: CLIENTE
-- ============================================================================

CREATE TABLE CLIENTE (
    CLIENTEID       NUMBER(10) DEFAULT SEQ_CLIENTE.NEXTVAL PRIMARY KEY,
    CODIGO          VARCHAR2(20) NOT NULL UNIQUE,
    NOMBRECOMPLETO  VARCHAR2(200) NOT NULL,
    TIPODOCUMENTO   VARCHAR2(20) DEFAULT 'Cedula' NOT NULL,
    NUMERODOCUMENTO VARCHAR2(20),
    EMAIL           VARCHAR2(150),
    TELEFONO        VARCHAR2(20),
    DIRECCION       VARCHAR2(300),
    CIUDAD          VARCHAR2(100) NOT NULL,
    PAIS            VARCHAR2(100) DEFAULT 'Ecuador' NOT NULL,
    FECHAREGISTRO   TIMESTAMP DEFAULT SYSTIMESTAMP,
    ACTIVO          NUMBER(1) DEFAULT 1
);

-- ============================================================================
-- TABLA: MODALIDAD_PAGO
-- ============================================================================

CREATE TABLE MODALIDAD_PAGO (
    MODALIDADPAGOID NUMBER(10) DEFAULT SEQ_MODALIDAD_PAGO.NEXTVAL PRIMARY KEY,
    CODIGO          VARCHAR2(20) NOT NULL UNIQUE,
    DESCRIPCION     VARCHAR2(100) NOT NULL,
    TIPOPAGO        VARCHAR2(50) NOT NULL,
    CUOTAS          NUMBER(5) DEFAULT 0 NOT NULL,
    TASAINTERES     NUMBER(5,2) DEFAULT 0,
    REQUIEREDATOS   NUMBER(1) DEFAULT 0,
    ACTIVO          NUMBER(1) DEFAULT 1,
    
    CONSTRAINT CK_MODALIDAD_CUOTAS CHECK (CUOTAS >= 0 AND CUOTAS <= 24),
    CONSTRAINT CK_MODALIDAD_TIPOPAGO CHECK (TIPOPAGO IN ('EFECTIVO', 'TRANSFERENCIA', 'TARJETA_CREDITO', 'TARJETA_DEBITO'))
);

-- ============================================================================
-- TABLA: PRODUCTO
-- ============================================================================

CREATE TABLE PRODUCTO (
    PRODUCTOID      NUMBER(10) DEFAULT SEQ_PRODUCTO.NEXTVAL PRIMARY KEY,
    CODIGO          VARCHAR2(30) NOT NULL UNIQUE,
    NOMBRE          VARCHAR2(200) NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    CATEGORIAID     NUMBER(10) NOT NULL,
    PROVEEDORID     NUMBER(10) NOT NULL,
    PRECIOUNITARIO  NUMBER(18,2) NOT NULL,
    PORCENTAJEIVA   NUMBER(5,2) DEFAULT 15.00 NOT NULL,
    STOCK           NUMBER(10) DEFAULT 0 NOT NULL,
    STOCKMINIMO     NUMBER(10) DEFAULT 10 NOT NULL,
    FECHACREACION   TIMESTAMP DEFAULT SYSTIMESTAMP,
    ACTIVO          NUMBER(1) DEFAULT 1,
    
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (CATEGORIAID) 
        REFERENCES CATEGORIA(CATEGORIAID),
    CONSTRAINT FK_PRODUCTO_PROVEEDOR FOREIGN KEY (PROVEEDORID) 
        REFERENCES PROVEEDOR(PROVEEDORID),
    CONSTRAINT CK_PRODUCTO_PRECIO CHECK (PRECIOUNITARIO > 0),
    CONSTRAINT CK_PRODUCTO_IVA CHECK (PORCENTAJEIVA IN (0, 15))
);

-- Indices para busquedas
CREATE INDEX IX_PRODUCTO_CATEGORIA ON PRODUCTO(CATEGORIAID);
CREATE INDEX IX_PRODUCTO_PROVEEDOR ON PRODUCTO(PROVEEDORID);

-- ============================================================================
-- TABLA: PEDIDO
-- ============================================================================

CREATE TABLE PEDIDO (
    PEDIDOID        NUMBER(10) DEFAULT SEQ_PEDIDO.NEXTVAL PRIMARY KEY,
    NUMEROPEDIDO    VARCHAR2(20) NOT NULL UNIQUE,
    FECHA           DATE NOT NULL,
    CLIENTEID       NUMBER(10) NOT NULL,
    EMPLEADOID      NUMBER(10) NOT NULL,
    MODALIDADPAGOID NUMBER(10) NOT NULL,
    SUBTOTAL        NUMBER(18,2) DEFAULT 0 NOT NULL,
    TOTALIVA        NUMBER(18,2) DEFAULT 0 NOT NULL,
    TOTAL           NUMBER(18,2) DEFAULT 0 NOT NULL,
    ESTADO          VARCHAR2(20) DEFAULT 'COMPLETADO' NOT NULL,
    OBSERVACIONES   VARCHAR2(500),
    FECHACREACION   TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CLIENTEID) 
        REFERENCES CLIENTE(CLIENTEID),
    CONSTRAINT FK_PEDIDO_EMPLEADO FOREIGN KEY (EMPLEADOID) 
        REFERENCES EMPLEADO(EMPLEADOID),
    CONSTRAINT FK_PEDIDO_MODALIDADPAGO FOREIGN KEY (MODALIDADPAGOID) 
        REFERENCES MODALIDAD_PAGO(MODALIDADPAGOID),
    CONSTRAINT CK_PEDIDO_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'PROCESANDO', 'COMPLETADO', 'CANCELADO'))
);

-- Indices para optimizar consultas
CREATE INDEX IX_PEDIDO_FECHA ON PEDIDO(FECHA);
CREATE INDEX IX_PEDIDO_CLIENTE ON PEDIDO(CLIENTEID);
CREATE INDEX IX_PEDIDO_EMPLEADO ON PEDIDO(EMPLEADOID);
CREATE INDEX IX_PEDIDO_MODALIDADPAGO ON PEDIDO(MODALIDADPAGOID);

-- ============================================================================
-- TABLA: DETALLE_PEDIDO
-- ============================================================================

CREATE TABLE DETALLE_PEDIDO (
    DETALLEID       NUMBER(10) DEFAULT SEQ_DETALLE_PEDIDO.NEXTVAL PRIMARY KEY,
    PEDIDOID        NUMBER(10) NOT NULL,
    PRODUCTOID      NUMBER(10) NOT NULL,
    CANTIDAD        NUMBER(10) NOT NULL,
    PRECIOUNITARIO  NUMBER(18,2) NOT NULL,
    PORCENTAJEIVA   NUMBER(5,2) NOT NULL,
    SUBTOTAL        NUMBER(18,2) NOT NULL,
    MONTOIVA        NUMBER(18,2) NOT NULL,
    TOTAL           NUMBER(18,2) NOT NULL,
    
    CONSTRAINT FK_DETALLE_PEDIDO FOREIGN KEY (PEDIDOID) 
        REFERENCES PEDIDO(PEDIDOID) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (PRODUCTOID) 
        REFERENCES PRODUCTO(PRODUCTOID),
    CONSTRAINT CK_DETALLE_CANTIDAD CHECK (CANTIDAD >= 1 AND CANTIDAD <= 50)
);

-- Indices
CREATE INDEX IX_DETALLE_PEDIDO ON DETALLE_PEDIDO(PEDIDOID);
CREATE INDEX IX_DETALLE_PRODUCTO ON DETALLE_PEDIDO(PRODUCTOID);

-- ============================================================================
-- VERIFICACION
-- ============================================================================

SELECT 'ESQUEMA OLTP ORACLE CREADO EXITOSAMENTE' AS MENSAJE FROM DUAL;

SELECT TABLE_NAME AS TABLA 
FROM USER_TABLES 
WHERE TABLE_NAME IN ('CATEGORIA','PROVEEDOR','EMPLEADO','CLIENTE','MODALIDAD_PAGO','PRODUCTO','PEDIDO','DETALLE_PEDIDO')
ORDER BY TABLE_NAME;

COMMIT;
