-- ============================================================================
-- PROYECTO OLAP - SISTEMA DE PEDIDOS
-- ============================================================================
-- Archivo: Tablas.sql
-- Descripcion: Esquema OLTP completo para sistema de pedidos (ORACLE)
-- Base de Datos: Oracle Database 21c
-- Fecha: Diciembre 2025
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;
SET LINESIZE 200;
SET PAGESIZE 100;

-- ============================================================================
-- LIMPIEZA COMPLETA
-- ============================================================================

DECLARE
    v_count NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Limpiando tablas existentes...');
    
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN 
              ('DETALLE_PEDIDO','PEDIDO','PRODUCTO','MODALIDAD_PAGO','CLIENTE','EMPLEADO','PROVEEDOR','CATEGORIA')) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
            DBMS_OUTPUT.PUT_LINE('  Tabla ' || t.table_name || ' eliminada.');
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    
    FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'SEQ_%') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('Limpieza completada.');
END;
/

-- ============================================================================
-- CREAR SECUENCIAS
-- ============================================================================

CREATE SEQUENCE SEQ_CATEGORIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROVEEDOR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EMPLEADO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MODALIDAD_PAGO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCTO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PEDIDO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DETALLE_PEDIDO START WITH 1 INCREMENT BY 1 NOCACHE;

BEGIN DBMS_OUTPUT.PUT_LINE('Secuencias creadas.'); END;
/

-- ============================================================================
-- TABLA: CATEGORIA
-- ============================================================================

CREATE TABLE CATEGORIA (
    CATEGORIAID     NUMBER(10) PRIMARY KEY,
    CODIGO          VARCHAR2(10) NOT NULL UNIQUE,
    NOMBRE          VARCHAR2(100) NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    FECHACREACION   TIMESTAMP DEFAULT SYSTIMESTAMP,
    ACTIVO          NUMBER(1) DEFAULT 1
);

BEGIN DBMS_OUTPUT.PUT_LINE('Tabla CATEGORIA creada.'); END;
/

-- ============================================================================
-- TABLA: PROVEEDOR
-- ============================================================================

CREATE TABLE PROVEEDOR (
    PROVEEDORID     NUMBER(10) PRIMARY KEY,
    CODIGO          VARCHAR2(20) NOT NULL UNIQUE,
    NOMBRE          VARCHAR2(200) NOT NULL,
    NOMBRECONTACTO  VARCHAR2(150),
    TELEFONO        VARCHAR2(20),
    EMAIL           VARCHAR2(150),
    DIRECCION       VARCHAR2(300),
    CIUDAD          VARCHAR2(100) NOT NULL,
    PAIS            VARCHAR2(100) DEFAULT 'Ecuador' NOT NULL,
    FECHACREACION   TIMESTAMP DEFAULT SYSTIMESTAMP,
    ACTIVO          NUMBER(1) DEFAULT 1
);

BEGIN DBMS_OUTPUT.PUT_LINE('Tabla PROVEEDOR creada.'); END;
/

-- ============================================================================
-- TABLA: EMPLEADO
-- ============================================================================

CREATE TABLE EMPLEADO (
    EMPLEADOID      NUMBER(10) PRIMARY KEY,
    CODIGO          VARCHAR2(20) NOT NULL UNIQUE,
    NOMBRECOMPLETO  VARCHAR2(200) NOT NULL,
    CARGO           VARCHAR2(100) DEFAULT 'Vendedor' NOT NULL,
    EMAIL           VARCHAR2(150),
    TELEFONO        VARCHAR2(20),
    FECHACONTRATACION DATE DEFAULT SYSDATE NOT NULL,
    ACTIVO          NUMBER(1) DEFAULT 1
);

BEGIN DBMS_OUTPUT.PUT_LINE('Tabla EMPLEADO creada.'); END;
/

-- ============================================================================
-- TABLA: CLIENTE
-- ============================================================================

CREATE TABLE CLIENTE (
    CLIENTEID       NUMBER(10) PRIMARY KEY,
    CODIGO          VARCHAR2(20) NOT NULL UNIQUE,
    NOMBRECOMPLETO  VARCHAR2(200) NOT NULL,
    TIPODOCUMENTO   VARCHAR2(20) DEFAULT 'Cedula' NOT NULL,
    NUMERODOCUMENTO VARCHAR2(20),
    EMAIL           VARCHAR2(150),
    TELEFONO        VARCHAR2(20),
    DIRECCION       VARCHAR2(300),
    CIUDAD          VARCHAR2(100) NOT NULL,
    PAIS            VARCHAR2(100) DEFAULT 'Ecuador' NOT NULL,
    FECHAREGISTRO   TIMESTAMP DEFAULT SYSTIMESTAMP,
    ACTIVO          NUMBER(1) DEFAULT 1
);

BEGIN DBMS_OUTPUT.PUT_LINE('Tabla CLIENTE creada.'); END;
/

-- ============================================================================
-- TABLA: MODALIDAD_PAGO
-- ============================================================================

CREATE TABLE MODALIDAD_PAGO (
    MODALIDADPAGOID NUMBER(10) PRIMARY KEY,
    CODIGO          VARCHAR2(20) NOT NULL UNIQUE,
    DESCRIPCION     VARCHAR2(100) NOT NULL,
    TIPOPAGO        VARCHAR2(50) NOT NULL,
    CUOTAS          NUMBER(5) DEFAULT 0 NOT NULL,
    TASAINTERES     NUMBER(5,2) DEFAULT 0,
    REQUIEREDATOS   NUMBER(1) DEFAULT 0,
    ACTIVO          NUMBER(1) DEFAULT 1
);

BEGIN DBMS_OUTPUT.PUT_LINE('Tabla MODALIDAD_PAGO creada.'); END;
/

-- ============================================================================
-- TABLA: PRODUCTO (sin FK inline - se agregan despues)
-- ============================================================================

CREATE TABLE PRODUCTO (
    PRODUCTOID      NUMBER(10) PRIMARY KEY,
    CODIGO          VARCHAR2(30) NOT NULL UNIQUE,
    NOMBRE          VARCHAR2(200) NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    CATEGORIAID     NUMBER(10) NOT NULL,
    PROVEEDORID     NUMBER(10) NOT NULL,
    PRECIOUNITARIO  NUMBER(18,2) NOT NULL,
    PORCENTAJEIVA   NUMBER(5,2) DEFAULT 15.00 NOT NULL,
    STOCK           NUMBER(10) DEFAULT 0 NOT NULL,
    STOCKMINIMO     NUMBER(10) DEFAULT 10 NOT NULL,
    FECHACREACION   TIMESTAMP DEFAULT SYSTIMESTAMP,
    ACTIVO          NUMBER(1) DEFAULT 1
);

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PROD_CAT FOREIGN KEY (CATEGORIAID) REFERENCES CATEGORIA(CATEGORIAID);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PROD_PROV FOREIGN KEY (PROVEEDORID) REFERENCES PROVEEDOR(PROVEEDORID);

CREATE INDEX IX_PRODUCTO_CATEGORIA ON PRODUCTO(CATEGORIAID);
CREATE INDEX IX_PRODUCTO_PROVEEDOR ON PRODUCTO(PROVEEDORID);

BEGIN DBMS_OUTPUT.PUT_LINE('Tabla PRODUCTO creada.'); END;
/

-- ============================================================================
-- TABLA: PEDIDO (sin FK inline - se agregan despues)
-- ============================================================================

CREATE TABLE PEDIDO (
    PEDIDOID        NUMBER(10) PRIMARY KEY,
    NUMEROPEDIDO    VARCHAR2(20) NOT NULL UNIQUE,
    FECHA           DATE NOT NULL,
    CLIENTEID       NUMBER(10) NOT NULL,
    EMPLEADOID      NUMBER(10) NOT NULL,
    MODALIDADPAGOID NUMBER(10) NOT NULL,
    SUBTOTAL        NUMBER(18,2) DEFAULT 0 NOT NULL,
    TOTALIVA        NUMBER(18,2) DEFAULT 0 NOT NULL,
    TOTAL           NUMBER(18,2) DEFAULT 0 NOT NULL,
    ESTADO          VARCHAR2(20) DEFAULT 'COMPLETADO' NOT NULL,
    OBSERVACIONES   VARCHAR2(500),
    FECHACREACION   TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PED_CLI FOREIGN KEY (CLIENTEID) REFERENCES CLIENTE(CLIENTEID);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_PED_EMP FOREIGN KEY (EMPLEADOID) REFERENCES EMPLEADO(EMPLEADOID);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_PED_MOD FOREIGN KEY (MODALIDADPAGOID) REFERENCES MODALIDAD_PAGO(MODALIDADPAGOID);

CREATE INDEX IX_PEDIDO_FECHA ON PEDIDO(FECHA);
CREATE INDEX IX_PEDIDO_CLIENTE ON PEDIDO(CLIENTEID);
CREATE INDEX IX_PEDIDO_EMPLEADO ON PEDIDO(EMPLEADOID);
CREATE INDEX IX_PEDIDO_MODALIDADPAGO ON PEDIDO(MODALIDADPAGOID);

BEGIN DBMS_OUTPUT.PUT_LINE('Tabla PEDIDO creada.'); END;
/

-- ============================================================================
-- TABLA: DETALLE_PEDIDO (sin FK inline - se agregan despues)
-- ============================================================================

CREATE TABLE DETALLE_PEDIDO (
    DETALLEID       NUMBER(10) PRIMARY KEY,
    PEDIDOID        NUMBER(10) NOT NULL,
    PRODUCTOID      NUMBER(10) NOT NULL,
    CANTIDAD        NUMBER(10) NOT NULL,
    PRECIOUNITARIO  NUMBER(18,2) NOT NULL,
    PORCENTAJEIVA   NUMBER(5,2) NOT NULL,
    SUBTOTAL        NUMBER(18,2) NOT NULL,
    MONTOIVA        NUMBER(18,2) NOT NULL,
    TOTAL           NUMBER(18,2) NOT NULL
);

ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT FK_DET_PED FOREIGN KEY (PEDIDOID) REFERENCES PEDIDO(PEDIDOID) ON DELETE CASCADE;
ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT FK_DET_PROD FOREIGN KEY (PRODUCTOID) REFERENCES PRODUCTO(PRODUCTOID);

CREATE INDEX IX_DETALLE_PEDIDO ON DETALLE_PEDIDO(PEDIDOID);
CREATE INDEX IX_DETALLE_PRODUCTO ON DETALLE_PEDIDO(PRODUCTOID);

BEGIN DBMS_OUTPUT.PUT_LINE('Tabla DETALLE_PEDIDO creada.'); END;
/

-- ============================================================================
-- TRIGGERS PARA AUTO-INCREMENTO (Compatible con Oracle 11g+)
-- ============================================================================

CREATE OR REPLACE TRIGGER TRG_CATEGORIA_ID
BEFORE INSERT ON CATEGORIA FOR EACH ROW
BEGIN
    IF :NEW.CATEGORIAID IS NULL THEN
        SELECT SEQ_CATEGORIA.NEXTVAL INTO :NEW.CATEGORIAID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PROVEEDOR_ID
BEFORE INSERT ON PROVEEDOR FOR EACH ROW
BEGIN
    IF :NEW.PROVEEDORID IS NULL THEN
        SELECT SEQ_PROVEEDOR.NEXTVAL INTO :NEW.PROVEEDORID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EMPLEADO_ID
BEFORE INSERT ON EMPLEADO FOR EACH ROW
BEGIN
    IF :NEW.EMPLEADOID IS NULL THEN
        SELECT SEQ_EMPLEADO.NEXTVAL INTO :NEW.EMPLEADOID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CLIENTE_ID
BEFORE INSERT ON CLIENTE FOR EACH ROW
BEGIN
    IF :NEW.CLIENTEID IS NULL THEN
        SELECT SEQ_CLIENTE.NEXTVAL INTO :NEW.CLIENTEID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_MODALIDAD_PAGO_ID
BEFORE INSERT ON MODALIDAD_PAGO FOR EACH ROW
BEGIN
    IF :NEW.MODALIDADPAGOID IS NULL THEN
        SELECT SEQ_MODALIDAD_PAGO.NEXTVAL INTO :NEW.MODALIDADPAGOID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTO_ID
BEFORE INSERT ON PRODUCTO FOR EACH ROW
BEGIN
    IF :NEW.PRODUCTOID IS NULL THEN
        SELECT SEQ_PRODUCTO.NEXTVAL INTO :NEW.PRODUCTOID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PEDIDO_ID
BEFORE INSERT ON PEDIDO FOR EACH ROW
BEGIN
    IF :NEW.PEDIDOID IS NULL THEN
        SELECT SEQ_PEDIDO.NEXTVAL INTO :NEW.PEDIDOID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DETALLE_PEDIDO_ID
BEFORE INSERT ON DETALLE_PEDIDO FOR EACH ROW
BEGIN
    IF :NEW.DETALLEID IS NULL THEN
        SELECT SEQ_DETALLE_PEDIDO.NEXTVAL INTO :NEW.DETALLEID FROM DUAL;
    END IF;
END;
/

-- ============================================================================
-- VERIFICACION
-- ============================================================================

SELECT 'ESQUEMA OLTP ORACLE CREADO EXITOSAMENTE' AS MENSAJE FROM DUAL;

SELECT TABLE_NAME AS TABLA 
FROM USER_TABLES 
WHERE TABLE_NAME IN ('CATEGORIA','PROVEEDOR','EMPLEADO','CLIENTE','MODALIDAD_PAGO','PRODUCTO','PEDIDO','DETALLE_PEDIDO')
ORDER BY TABLE_NAME;

COMMIT;
