-- 1) Crear tablas de respaldo (solo si no existen)
CREATE TABLE ORDENES_BACKUP AS
SELECT * FROM ORDENES WHERE 1 = 0;

CREATE TABLE DETALLE_ORDENES_BACKUP AS
SELECT * FROM DETALLE_ORDENES WHERE 1 = 0;

-- 2) Respaldo en caliente (BD operativa)
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

LOCK TABLE ORDENES IN SHARE MODE;
LOCK TABLE DETALLE_ORDENES IN SHARE MODE;

INSERT INTO ORDENES_BACKUP
SELECT * FROM ORDENES;

INSERT INTO DETALLE_ORDENES_BACKUP
SELECT * FROM DETALLE_ORDENES;

COMMIT;

-- 3) Verificación
SELECT COUNT(*) AS ORDENES_ORIGINAL FROM ORDENES;
SELECT COUNT(*) AS ORDENES_RESPALDO  FROM ORDENES_BACKUP;

SELECT COUNT(*) AS DETALLE_ORIGINAL  FROM DETALLE_ORDENES;
SELECT COUNT(*) AS DETALLE_RESPALDO  FROM DETALLE_ORDENES_BACKUP;